name: CMake Build and Test

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get install cmake build-essential
        sudo apt install libelf-dev libcapstone-dev

    - name: Create build directory
      run: mkdir build

    - name: Configure CMake
      run: cd build && cmake ..

    - name: Build project
      run: cd build && cmake --build .

    - name: Run tests
      run: cd build && ctest